[package]
name = "fifa_sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.dev]
opt-level = 3


[dependencies]
# csv = "1.1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
crossterm = { version = "0.25", features = [ "serde" ] }
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.8.5", default-features = false, features = ["std"] }
tui = { version = "0.18", default-features = false, features = ['crossterm', 'serde'] }
tokio = { version = "1", features = ["full"] }

log = "0.4"
tui-logger = "0.8"
tui-textarea = "0.1.5"
csv = "1.1"
tokio-stream = "0.1"